import type { DevOpsComponent } from "@/types/architecture"

// Google Cloud regions for dropdown
export const gcpRegions = [
  { value: "us-central1", label: "Iowa (us-central1)" },
  { value: "us-east1", label: "South Carolina (us-east1)" },
  { value: "us-east4", label: "Virginia (us-east4)" },
  { value: "us-west1", label: "Oregon (us-west1)" },
  { value: "us-west2", label: "Los Angeles (us-west2)" },
  { value: "europe-west1", label: "Belgium (europe-west1)" },
  { value: "europe-west2", label: "London (europe-west2)" },
  { value: "europe-west3", label: "Frankfurt (europe-west3)" },
  { value: "asia-east1", label: "Taiwan (asia-east1)" },
  { value: "asia-southeast1", label: "Singapore (asia-southeast1)" },
  { value: "asia-south1", label: "Mumbai (asia-south1)" },
  { value: "australia-southeast1", label: "Sydney (australia-southeast1)" },
]

// Machine types for Compute Engine
export const machineTypes = [
  { value: "e2-micro", label: "e2-micro (2 vCPU, 1 GB)", cost: 6.11 },
  { value: "e2-small", label: "e2-small (2 vCPU, 2 GB)", cost: 12.23 },
  { value: "e2-medium", label: "e2-medium (2 vCPU, 4 GB)", cost: 24.46 },
  { value: "e2-standard-2", label: "e2-standard-2 (2 vCPU, 8 GB)", cost: 48.92 },
  { value: "e2-standard-4", label: "e2-standard-4 (4 vCPU, 16 GB)", cost: 97.83 },
  { value: "e2-standard-8", label: "e2-standard-8 (8 vCPU, 32 GB)", cost: 195.67 },
  { value: "n2-standard-2", label: "n2-standard-2 (2 vCPU, 8 GB)", cost: 71.54 },
  { value: "n2-standard-4", label: "n2-standard-4 (4 vCPU, 16 GB)", cost: 143.08 },
  { value: "n2-standard-8", label: "n2-standard-8 (8 vCPU, 32 GB)", cost: 286.16 },
]

// Cloud Functions memory options
export const functionMemory = [
  { value: "128MB", label: "128 MB" },
  { value: "256MB", label: "256 MB" },
  { value: "512MB", label: "512 MB" },
  { value: "1024MB", label: "1 GB" },
  { value: "2048MB", label: "2 GB" },
  { value: "4096MB", label: "4 GB" },
  { value: "8192MB", label: "8 GB" },
]

// Cloud SQL instance types
export const sqlInstanceTypes = [
  { value: "db-f1-micro", label: "db-f1-micro (Shared, 0.6 GB)", cost: 7.67 },
  { value: "db-g1-small", label: "db-g1-small (Shared, 1.7 GB)", cost: 25.55 },
  { value: "db-n1-standard-1", label: "db-n1-standard-1 (1 vCPU, 3.75 GB)", cost: 51.1 },
  { value: "db-n1-standard-2", label: "db-n1-standard-2 (2 vCPU, 7.5 GB)", cost: 102.2 },
  { value: "db-n1-standard-4", label: "db-n1-standard-4 (4 vCPU, 15 GB)", cost: 204.4 },
  { value: "db-n1-highmem-2", label: "db-n1-highmem-2 (2 vCPU, 13 GB)", cost: 130.0 },
]

// Autoscaling options
export const autoscaleOptions = [
  { value: "disabled", label: "Disabled" },
  { value: "cpu-50", label: "CPU > 50%" },
  { value: "cpu-70", label: "CPU > 70%" },
  { value: "cpu-80", label: "CPU > 80%" },
  { value: "requests", label: "Request Count Based" },
  { value: "custom", label: "Custom Metric" },
]

export const minInstanceOptions = [
  { value: "0", label: "0 (Scale to zero)" },
  { value: "1", label: "1 instance" },
  { value: "2", label: "2 instances" },
  { value: "3", label: "3 instances" },
  { value: "5", label: "5 instances" },
]

export const maxInstanceOptions = [
  { value: "1", label: "1 instance" },
  { value: "3", label: "3 instances" },
  { value: "5", label: "5 instances" },
  { value: "10", label: "10 instances" },
  { value: "20", label: "20 instances" },
  { value: "50", label: "50 instances" },
  { value: "100", label: "100 instances" },
]

export const devOpsComponents: DevOpsComponent[] = [
  // Compute
  {
    id: "compute-engine",
    type: "compute-engine",
    category: "compute",
    name: "Compute Engine",
    description: "Virtual machine instances",
    icon: "Server",
    defaultConfig: {
      machineType: "e2-medium",
      region: "us-central1",
      diskSize: "50",
      diskType: "pd-balanced",
      autoscale: "disabled",
      minInstances: "1",
      maxInstances: "5",
    },
    baseCost: 24.46,
    allowedConnections: ["vpc-network", "cloud-sql", "cloud-storage", "load-balancer", "firewall", "memorystore"],
  },
  {
    id: "cloud-functions",
    type: "cloud-functions",
    category: "compute",
    name: "Cloud Functions",
    description: "Serverless functions",
    icon: "Zap",
    defaultConfig: {
      runtime: "nodejs20",
      memory: "256MB",
      region: "us-central1",
      timeout: "60",
      minInstances: "0",
      maxInstances: "100",
    },
    baseCost: 0,
    allowedConnections: ["cloud-storage", "cloud-sql", "firestore", "pub-sub", "api-gateway"],
  },
  {
    id: "cloud-run",
    type: "cloud-run",
    category: "compute",
    name: "Cloud Run",
    description: "Serverless containers",
    icon: "Container",
    defaultConfig: {
      memory: "512MB",
      cpu: "1",
      region: "us-central1",
      minInstances: "0",
      maxInstances: "10",
      autoscale: "cpu-70",
    },
    baseCost: 0,
    allowedConnections: ["cloud-sql", "cloud-storage", "memorystore", "vpc-network", "load-balancer"],
  },
  {
    id: "gke",
    type: "gke",
    category: "compute",
    name: "GKE Cluster",
    description: "Managed Kubernetes",
    icon: "Boxes",
    defaultConfig: {
      machineType: "e2-standard-2",
      region: "us-central1",
      nodeCount: "3",
      autoscale: "cpu-70",
      minNodes: "1",
      maxNodes: "10",
    },
    baseCost: 74.4,
    allowedConnections: [
      "vpc-network",
      "cloud-sql",
      "cloud-storage",
      "memorystore",
      "load-balancer",
      "artifact-registry",
    ],
  },
  {
    id: "app-engine",
    type: "app-engine",
    category: "compute",
    name: "App Engine",
    description: "Fully managed platform",
    icon: "Layers",
    defaultConfig: {
      runtime: "nodejs20",
      instanceClass: "F2",
      region: "us-central1",
      autoscale: "cpu-50",
      minInstances: "0",
      maxInstances: "10",
    },
    baseCost: 0,
    allowedConnections: ["cloud-sql", "cloud-storage", "memorystore", "firestore"],
  },
  // Networking
  {
    id: "vpc-network",
    type: "vpc-network",
    category: "networking",
    name: "VPC Network",
    description: "Virtual private cloud",
    icon: "Network",
    defaultConfig: {
      subnetMode: "auto",
      region: "us-central1",
      ipRange: "10.0.0.0/16",
    },
    baseCost: 0,
    allowedConnections: ["compute-engine", "gke", "cloud-run", "cloud-sql", "memorystore"],
  },
  {
    id: "load-balancer",
    type: "load-balancer",
    category: "networking",
    name: "Cloud Load Balancing",
    description: "Global load balancer",
    icon: "Split",
    defaultConfig: {
      type: "http",
      region: "global",
      sslEnabled: "true",
    },
    baseCost: 18.0,
    allowedConnections: ["compute-engine", "gke", "cloud-run", "cloud-storage"],
  },
  {
    id: "cloud-cdn",
    type: "cloud-cdn",
    category: "networking",
    name: "Cloud CDN",
    description: "Content delivery network",
    icon: "Wifi",
    defaultConfig: {
      cacheMode: "CACHE_ALL_STATIC",
      region: "global",
    },
    baseCost: 0,
    allowedConnections: ["load-balancer", "cloud-storage"],
  },
  {
    id: "cloud-dns",
    type: "cloud-dns",
    category: "networking",
    name: "Cloud DNS",
    description: "Domain name system",
    icon: "Globe",
    defaultConfig: {
      visibility: "public",
    },
    baseCost: 0.2,
    allowedConnections: ["load-balancer", "compute-engine", "cloud-run"],
  },
  {
    id: "api-gateway",
    type: "api-gateway",
    category: "networking",
    name: "API Gateway",
    description: "API management",
    icon: "GitBranch",
    defaultConfig: {
      region: "us-central1",
    },
    baseCost: 0,
    allowedConnections: ["cloud-functions", "cloud-run", "gke"],
  },
  // Storage
  {
    id: "cloud-storage",
    type: "cloud-storage",
    category: "storage",
    name: "Cloud Storage",
    description: "Object storage buckets",
    icon: "Database",
    defaultConfig: {
      storageClass: "STANDARD",
      region: "us-central1",
      versioning: "disabled",
    },
    baseCost: 0,
    allowedConnections: ["compute-engine", "cloud-functions", "cloud-run", "gke", "cloud-cdn"],
  },
  {
    id: "cloud-sql",
    type: "cloud-sql",
    category: "storage",
    name: "Cloud SQL",
    description: "Managed MySQL/PostgreSQL",
    icon: "HardDrive",
    defaultConfig: {
      databaseType: "postgresql",
      instanceType: "db-n1-standard-1",
      region: "us-central1",
      storageSize: "100",
      highAvailability: "disabled",
    },
    baseCost: 51.1,
    allowedConnections: ["vpc-network", "compute-engine", "cloud-functions", "cloud-run", "gke", "app-engine"],
  },
  {
    id: "firestore",
    type: "firestore",
    category: "storage",
    name: "Cloud Firestore",
    description: "NoSQL document database",
    icon: "Table",
    defaultConfig: {
      mode: "native",
      region: "us-central1",
    },
    baseCost: 0,
    allowedConnections: ["cloud-functions", "cloud-run", "app-engine", "compute-engine"],
  },
  {
    id: "memorystore",
    type: "memorystore",
    category: "storage",
    name: "Memorystore",
    description: "Managed Redis/Memcached",
    icon: "Gauge",
    defaultConfig: {
      engine: "redis",
      tier: "basic",
      memorySizeGb: "1",
      region: "us-central1",
    },
    baseCost: 35.04,
    allowedConnections: ["vpc-network", "compute-engine", "cloud-run", "gke", "app-engine"],
  },
  {
    id: "bigtable",
    type: "bigtable",
    category: "storage",
    name: "Cloud Bigtable",
    description: "Wide-column NoSQL",
    icon: "LayoutGrid",
    defaultConfig: {
      clusterType: "production",
      nodes: "3",
      region: "us-central1",
    },
    baseCost: 455.0,
    allowedConnections: ["compute-engine", "cloud-functions", "gke"],
  },
  // Security
  {
    id: "firewall",
    type: "firewall",
    category: "security",
    name: "VPC Firewall",
    description: "Network firewall rules",
    icon: "Shield",
    defaultConfig: {
      direction: "ingress",
      priority: "1000",
      action: "allow",
    },
    baseCost: 0,
    allowedConnections: ["vpc-network", "compute-engine", "gke"],
  },
  {
    id: "iam",
    type: "iam",
    category: "security",
    name: "IAM & Admin",
    description: "Identity and access",
    icon: "Key",
    defaultConfig: {
      roleType: "predefined",
    },
    baseCost: 0,
    allowedConnections: ["cloud-functions", "compute-engine", "cloud-run", "gke", "cloud-storage"],
  },
  {
    id: "cloud-armor",
    type: "cloud-armor",
    category: "security",
    name: "Cloud Armor",
    description: "DDoS protection & WAF",
    icon: "ShieldCheck",
    defaultConfig: {
      policyType: "standard",
    },
    baseCost: 5.0,
    allowedConnections: ["load-balancer"],
  },
  {
    id: "secret-manager",
    type: "secret-manager",
    category: "security",
    name: "Secret Manager",
    description: "Secrets management",
    icon: "Lock",
    defaultConfig: {
      replicationPolicy: "automatic",
    },
    baseCost: 0,
    allowedConnections: ["cloud-functions", "compute-engine", "cloud-run", "gke", "app-engine"],
  },
  // Monitoring
  {
    id: "cloud-monitoring",
    type: "cloud-monitoring",
    category: "monitoring",
    name: "Cloud Monitoring",
    description: "Metrics and alerting",
    icon: "Activity",
    defaultConfig: {
      alertingEnabled: "true",
    },
    baseCost: 0,
    allowedConnections: ["compute-engine", "cloud-functions", "cloud-run", "gke", "cloud-sql"],
  },
  {
    id: "cloud-logging",
    type: "cloud-logging",
    category: "monitoring",
    name: "Cloud Logging",
    description: "Log management",
    icon: "FileText",
    defaultConfig: {
      retentionDays: "30",
    },
    baseCost: 0,
    allowedConnections: ["compute-engine", "cloud-functions", "cloud-run", "gke", "cloud-sql"],
  },
  {
    id: "pub-sub",
    type: "pub-sub",
    category: "monitoring",
    name: "Pub/Sub",
    description: "Messaging service",
    icon: "Bell",
    defaultConfig: {
      messageRetention: "7",
      region: "us-central1",
    },
    baseCost: 0,
    allowedConnections: ["cloud-functions", "cloud-run", "gke", "compute-engine"],
  },
  {
    id: "cloud-trace",
    type: "cloud-trace",
    category: "monitoring",
    name: "Cloud Trace",
    description: "Distributed tracing",
    icon: "Radar",
    defaultConfig: {
      samplingRate: "0.1",
    },
    baseCost: 0,
    allowedConnections: ["cloud-functions", "cloud-run", "gke", "app-engine"],
  },
  // Container Registry
  {
    id: "artifact-registry",
    type: "artifact-registry",
    category: "storage",
    name: "Artifact Registry",
    description: "Container & package registry",
    icon: "Package",
    defaultConfig: {
      format: "docker",
      region: "us-central1",
    },
    baseCost: 0,
    allowedConnections: ["cloud-run", "gke", "compute-engine"],
  },
]

export const componentCategories = [
  { id: "compute", name: "Compute", icon: "Cpu" },
  { id: "networking", name: "Networking", icon: "Network" },
  { id: "storage", name: "Storage", icon: "Database" },
  { id: "security", name: "Security", icon: "Shield" },
  { id: "monitoring", name: "Monitoring", icon: "Activity" },
]
