import type { CanvasComponent, Connection } from "@/types/architecture"

export function generateTerraform(components: CanvasComponent[], connections: Connection[]): string {
  let terraform = `# Generated by GCP Architecture Builder
# Terraform configuration for Google Cloud Platform

terraform {
  required_version = ">= 1.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

variable "project_id" {
  description = "The GCP project ID"
  type        = string
}

variable "region" {
  description = "The default region"
  type        = string
  default     = "us-central1"
}

provider "google" {
  project = var.project_id
  region  = var.region
}

`

  components.forEach((component) => {
    terraform += generateComponentTerraform(component, connections)
    terraform += "\n"
  })

  return terraform
}

function generateComponentTerraform(component: CanvasComponent, connections: Connection[]): string {
  const resourceName = component.name
    .toLowerCase()
    .replace(/\s+/g, "_")
    .replace(/[^a-z0-9_]/g, "")

  switch (component.type) {
    case "vpc-network":
      return `resource "google_compute_network" "${resourceName}" {
  name                    = "${resourceName}"
  auto_create_subnetworks = ${component.config.subnetMode === "auto"}
  project                 = var.project_id
}
`

    case "compute-engine":
      return `resource "google_compute_instance" "${resourceName}" {
  name         = "${resourceName}"
  machine_type = "${component.config.machineType || "e2-medium"}"
  zone         = "${component.config.region || "us-central1"}-a"
  project      = var.project_id

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-11"
      size  = ${component.config.diskSize || 50}
      type  = "${component.config.diskType || "pd-balanced"}"
    }
  }

  network_interface {
    network = "default"
    access_config {}
  }

  labels = {
    name = "${component.name}"
  }
}
`

    case "cloud-functions":
      return `resource "google_cloudfunctions2_function" "${resourceName}" {
  name     = "${resourceName}"
  location = "${component.config.region || "us-central1"}"
  project  = var.project_id

  build_config {
    runtime     = "${component.config.runtime || "nodejs20"}"
    entry_point = "main"
    source {
      storage_source {
        bucket = "YOUR_SOURCE_BUCKET"
        object = "function-source.zip"
      }
    }
  }

  service_config {
    max_instance_count = ${component.config.maxInstances || 100}
    min_instance_count = ${component.config.minInstances || 0}
    available_memory   = "${component.config.memory || "256MB"}"
    timeout_seconds    = ${component.config.timeout || 60}
  }
}
`

    case "cloud-run":
      return `resource "google_cloud_run_v2_service" "${resourceName}" {
  name     = "${resourceName}"
  location = "${component.config.region || "us-central1"}"
  project  = var.project_id

  template {
    scaling {
      min_instance_count = ${component.config.minInstances || 0}
      max_instance_count = ${component.config.maxInstances || 10}
    }
    containers {
      image = "gcr.io/\${var.project_id}/${resourceName}"
      resources {
        limits = {
          cpu    = "${component.config.cpu || "1"}"
          memory = "${component.config.memory || "512Mi"}"
        }
      }
    }
  }
}
`

    case "gke":
      return `resource "google_container_cluster" "${resourceName}" {
  name     = "${resourceName}"
  location = "${component.config.region || "us-central1"}"
  project  = var.project_id

  remove_default_node_pool = true
  initial_node_count       = 1
}

resource "google_container_node_pool" "${resourceName}_nodes" {
  name       = "${resourceName}-node-pool"
  location   = "${component.config.region || "us-central1"}"
  cluster    = google_container_cluster.${resourceName}.name
  node_count = ${component.config.nodeCount || 3}
  project    = var.project_id

  node_config {
    machine_type = "${component.config.machineType || "e2-standard-2"}"
  }

  autoscaling {
    min_node_count = ${component.config.minNodes || 1}
    max_node_count = ${component.config.maxNodes || 10}
  }
}
`

    case "cloud-storage":
      return `resource "google_storage_bucket" "${resourceName}" {
  name          = "\${var.project_id}-${resourceName}"
  location      = "${component.config.region || "US"}"
  project       = var.project_id
  storage_class = "${component.config.storageClass || "STANDARD"}"

  versioning {
    enabled = ${component.config.versioning === "enabled"}
  }
}
`

    case "cloud-sql":
      return `resource "google_sql_database_instance" "${resourceName}" {
  name             = "${resourceName}"
  database_version = "${component.config.databaseType === "mysql" ? "MYSQL_8_0" : "POSTGRES_15"}"
  region           = "${component.config.region || "us-central1"}"
  project          = var.project_id

  settings {
    tier = "${component.config.instanceType || "db-n1-standard-1"}"
    disk_size = ${component.config.storageSize || 100}

    availability_type = "${component.config.highAvailability === "enabled" ? "REGIONAL" : "ZONAL"}"
  }

  deletion_protection = false
}
`

    case "load-balancer":
      return `resource "google_compute_global_address" "${resourceName}_ip" {
  name    = "${resourceName}-ip"
  project = var.project_id
}

resource "google_compute_url_map" "${resourceName}" {
  name            = "${resourceName}"
  project         = var.project_id
  default_service = "YOUR_BACKEND_SERVICE"
}
`

    case "firewall":
      return `resource "google_compute_firewall" "${resourceName}" {
  name    = "${resourceName}"
  network = "default"
  project = var.project_id

  allow {
    protocol = "tcp"
    ports    = ["80", "443"]
  }

  source_ranges = ["0.0.0.0/0"]
}
`

    case "memorystore":
      return `resource "google_redis_instance" "${resourceName}" {
  name           = "${resourceName}"
  tier           = "${component.config.tier === "standard" ? "STANDARD_HA" : "BASIC"}"
  memory_size_gb = ${component.config.memorySizeGb || 1}
  region         = "${component.config.region || "us-central1"}"
  project        = var.project_id
}
`

    case "pub-sub":
      return `resource "google_pubsub_topic" "${resourceName}" {
  name    = "${resourceName}"
  project = var.project_id

  message_retention_duration = "${(Number.parseInt(String(component.config.messageRetention)) || 7) * 24 * 60 * 60}s"
}
`

    case "cloud-monitoring":
      return `resource "google_monitoring_alert_policy" "${resourceName}" {
  display_name = "${component.name} Alert Policy"
  project      = var.project_id
  combiner     = "OR"

  conditions {
    display_name = "CPU Utilization"
    condition_threshold {
      filter          = "metric.type=\"compute.googleapis.com/instance/cpu/utilization\""
      comparison      = "COMPARISON_GT"
      threshold_value = 0.8
      duration        = "60s"
    }
  }

  notification_channels = []
}
`

    default:
      return `# Resource: ${component.name} (${component.type})
# Add custom Terraform configuration for this GCP component
`
  }
}
